### ISSUE TITLE
Use FDW to automate access to de-id'd data.

### ISSUE THREAD

**Issue by johnmudd** [Kozea/Multicorn#108]
My goal is to be able to both encrypt and index the same fields. Encrypt it so I'm HIPAA compliant and index it so I can search quickly. Normally these are mutually exclusive. I read a suggestion to de-identify the fields instead. Here's how I imagine it working: [link](http://stackoverflow.com/a/32142088/487992).

Does an FDW seem like a good mechanism to automate this approach?

**Comment by rdunklau** [comment]
This problem is not specific to Multicorn. Please use the postgresql mailing lists :)
