### ISSUE TITLE
Convert foreign table to real?

### ISSUE THREAD

**Issue by johnmudd** [Kozea/Multicorn#113]
Any suggestions to convert a foreign table to real table?

So far I can use pg_dump to get the CREATE TABLE statement. After editing the output.

And I can use the following to dump the data. Is there a better approach?

COPY (SELECT * from my_fdw_table) TO STDOUT WITH CSV HEADER;

**Comment by rotten** [comment]
Wouldn't 'select into' work? -- http://www.postgresql.org/docs/9.4/static/sql-selectinto.html

**Comment by johnmudd** [comment]
SELECT INTO executes and creates the new table but the new table has no columns or rows.

**Comment by rdunklau** [comment]
What do you mean ? Could you post an example ?

Both forms work for me:

select * into table new_local_table from foreign_table;
create table new_local_table AS (select * from foreign_table);

**Comment by johnmudd** [comment]
You are correct, thanks! I tried "SELECT INTO" instead of "SELECT * INTO".
