### ISSUE TITLE
Recent change in make_foreignscan()

### ISSUE THREAD

**Issue by coreyatmoat** [Kozea/Multicorn#119]
A seventh parameter was added to make_foreignscan() on Oct 15th:

http://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=5043193b78919a1bd144563aadc2f7f726549913

This causes multicorn to fail to build on 9.5beta2

The fix is to add an extra ", NULL" to
https://github.com/Kozea/Multicorn/blob/master/src/multicorn.c#L359-L361

**Comment by rdunklau** [comment]
Thanks, fixed in 672625e8f18c23a8aea3f938043ca04f6995c7e1
