### ISSUE TITLE
Not bulding with 9.6

### ISSUE THREAD

**Issue by vinnix** [Kozea/Multicorn#166]
Hello, 

Since PG Hackers change some internal structures to support parallelism and so on,
Multicorn extension is not compiling/building with it.

Someone at IRC said that will not be a hard work to make it work with 9.6, but we
need check it better.

If I can help, please let me know.

**Comment by jeffjanes** [comment]
There is already a pull request for this, #137

If you have the ability to test it, please do.  As far as I can tell, it
works with both 9.6RC1, and with 10.dev

Cheers,

Jeff

**Comment by codekoala** [comment]
@jeffjanes it works great for me. Thanks for your work :)

**Comment by rdunklau** [comment]
Fixed by #137 , thank you
