### ISSUE TITLE
ldap does not work with ldap3 > 1.4.0

### ISSUE THREAD

**Issue by scheiblr** [Kozea/Multicorn#178]
Hi, ldap wrapper does not work with current versions of ldap3. I guess because some constants got renamed:
https://github.com/cannatag/ldap3/blob/a8e97fa6b3814e1339c90b2665f7338f1e4ca123/CHANGES.txt

**Comment by k1complete** [comment]
Hi, I make pull request for #181 .
Please check it or  [my fork](https://github.com/k1complete/Multicorn/tree/ldap3-2).
