### ISSUE TITLE
Makefile:54: /usr/pgsql-9.5/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory

### ISSUE THREAD

**Issue by littleWT** [Kozea/Multicorn#190]
when  I make multicorn with python2.6 or python3.5 ,it show me the error all the time.

> **Makefile:54: /usr/pgsql-9.5/lib/pgxs/src/makefiles/pgxs.mk: No such file or directory
> make: python2.6-config: Command not found
> expr: syntax error
> expr: syntax error
> Python version is 2.6
> make: *** No rule to make target `/usr/pgsql-9.5/lib/pgxs/src/makefiles/pgxs.mk'.  Stop.**

who can tell me how to deal the problem

**Comment by ChristophBerg** [comment]
Seems you are missing the PostgreSQL and Python -devel packages.

**Comment by seanfcarroll** [comment]
Backup your database, then

```
sudo apt-get install postgresql-server-dev-all
sudo apt-get install postgresql-common
```

**Comment by chenzuoli** [comment]
> Backup your database, then
> 
> ```
> sudo apt-get install postgresql-server-dev-all
> sudo apt-get install postgresql-common
> ```

i am centos7, how can i do this?

**Comment by seanfcarroll** [comment]
Open a terminal and then type those commands. Because you are using ```sudo``` you will need to provide a password.

I also suggest you do some reading on apt-get .... not always good to type in commands from the internet! ... but you can trust me, I promise :-)

**Comment by caiohamamura** [comment]
What about other systems which do not have the postgresql-server-dev packages to install? I'm using windows and compiled postgresql from source, but can't find pgxs.mk either.

**Comment by chenzuoli** [comment]
> > Backup your database, then
> > ```
> > sudo apt-get install postgresql-server-dev-all
> > sudo apt-get install postgresql-common
> > ```
> 
> i am centos7, how can i do this?

i run : yum install postgresql10-devel
then problem solved. if your pgsql version lower then 10 , run : yum install postgresql-devel

**Comment by galuszkak** [comment]
Closing as @chenzuoli reply is solving the problem.

**Comment by yasin0824github** [comment]
i'm encounter the same problem,, this is miss some libs for dev environment .you just run the command  "yum install postgresql12-devel" node that the number is your psql version.
