### ISSUE TITLE
python3.4 make error

### ISSUE THREAD

**Issue by qhq16** [Kozea/Multicorn#233]
ubuntu@i-9gzoo80x:~/Multicorn-master$ make
Python version is 3.4
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -g -O2 -DMAP_HUGETLB=0x40000 -fPIC -I. -I./ -I/opt/local/edb/languagepack-10/Python-3.4/include/python3.4m -I. -I./ -I/opt/pgsql/include/postgresql/server -I/opt/pgsql/include/postgresql/internal -I/opt/local/Current/include -D_GNU_SOURCE  -I/opt/local/Current/include/libxml2 -I/opt/local/Current/include  -c -o src/errors.o src/errors.c
In file included from src/errors.c:15:0:
src/multicorn.h:1:20: fatal error: Python.h: No such file or directory
compilation terminated.
<builtin>: recipe for target 'src/errors.o' failed
make: *** [src/errors.o] Error 1

But I have already installed the python3-dev, and even the python3.4-dev. This error existed however. My PG version is 10.9. Could you help me?

**Comment by KAction** [comment]
You have to provide more detailed information about your environment. But given you mentioned `python3-dev` I infer you are using Debian-based system. You may want to install `libpython3-dev` too and try again.

**Comment by qhq16** [comment]
I used Ubuntu16.04 system. And I found the 'Python.h'  under the dir '/usr/include/python3.4m'. But why did it can't be included in 'multicorn.h' or other files?

**Comment by Jopie01** [comment]
Use `PYTHON_OVERRIDE=python3 make`. It did work for me.

**Comment by qhq16** [comment]
Thanks, it worked!
