### ISSUE TITLE
Unable to see the fdw table in pgadmin?

### ISSUE THREAD

**Issue by johnmudd** [Kozea/Multicorn#29]
I created a csv fdw table following the example. I'm able to access the table and it works well. So I had another person connect to my db from a separate PC using pgadmin. They can't see the fdw table. Even thought they are using my user account.

If I create a regular table then that appears in pgAdmin. But not the fdw table from a remote PC.

Any suggestions?

I assume this has nothing to do with multicorn. I'm just posting this here so I can share my experience in case it helps others.

**Comment by 84zhu** [comment]
Google answers better than Baidu‘s，3Q’ @johnmudd
