### ISSUE TITLE
Expose limit clause to Multicorn FDW implementations

### ISSUE THREAD

**Issue by hhamalai** [Kozea/Multicorn#54]
Could the limit clause be exposed to Multicorn FDW implementations? This would be handy in cases where the foreign data source also has a limit-like functionality.

**Comment by bbigras** [comment]
Is it still the case today?

> This works as expected since version 12 with commit [d50d172e51](https://github.com/postgres/postgres/commit/d50d172e517c1d2aabff3ceb3ad3113b909c5017) indeed, but only for non-partitioned (non-sharded) tables.

https://dba.stackexchange.com/questions/242358/how-do-i-get-postgresql-fdw-to-push-down-the-limit-to-the-single-backend-serve

**Comment by bbigras** [comment]
@rdunklau friendly ping
