### ISSUE TITLE
key = any (array(select id from ...)) passed incorrectly

### ISSUE THREAD

**Issue by postsql** [Kozea/Multicorn#66]
It looks like array generated via a query is passed incorrectly in Qual:

testdb=# select \* from mytable where id = any (array(select mytable_id from acl where acl.member_id = 112));
NOTICE:  PK COL : id
NOTICE:  get_path_keys()
NOTICE:  [id = ANY(140273338805376)]

whereas a constant array gets passed correctly

testdb=# select \* from mytable where id = any (array[1,2,3,4,5]);
NOTICE:  PK COL : id
NOTICE:  get_path_keys()
NOTICE:  [id = ANY([u'1', u'2', u'3', u'4', u'5'])]

**Comment by frbsfri** [comment]
Any news on this bug? I have the same problem

```
postgres=# explain analyze verbose select * from table where  "pId" in('SCS931000123', 'SCS931000124');
ERROR:  Error in python: OSError
DETAIL:  [Errno 2] No such file or directory: "/home/Windows-Share/[u'SCS931000123', u'SCS931000124']"
```
