### ISSUE TITLE
WHERE statements are loosing their quotes

### ISSUE THREAD

**Issue by Bengreen** [Kozea/Multicorn#84]
When i make a WHERE statement against a table it is loosing the quotes before they are passed as qual parameters. As a result the value field of the qual does not have quotes and hence is not distinguishable from trying to make a match against another column of the name given in value.

e.g. 
    select age,name from constanttable WHERE name='Ben';
This results in a qual parameter of : [name = Ben]   when i log str(qual)
Which fails as it is NOT quoted. i could artifically add the quotes, but this seems incorrect as i would be prevented from matching to other columns (e.g. below)

If i want to run this query looking for a match of the column name with the text 'age'. Because of the missing quotes i cannot disambiguate the qual if this is supposed to be matching a column called age or the text 'age' in column name. I should be able to do both and would be able to if the quotes were passed down to the qual.
    select age,name from constanttable WHERE name='age';

Is this a feature that the quotes are stripped from the qual or a bug?
I would prefer to see the quotes preserved and passed down.

**Comment by rdunklau** [comment]
Several issues are about the same thing, closing this as duplicate.
