### ISSUE TITLE
Error in implementing a fdw documentation

### ISSUE THREAD

**Issue by jerowe** [Kozea/Multicorn#95]
http://multicorn.org/implementing-an-fdw/#idhow-do-we-do-that

The documentation is this:

CREATE SERVER multicorn_srv foreign data wrapper multicorn options (
    wrapper 'multicorn.myfdw.ConstantForeignDataWrapper'
    );

CREATE FOREIGN TABLE constanttable (
    test character varying,
    test2 character varying
) server multicorn_srv options (
    wrapper 'multicorn.myfdw.ConstantForeignDataWrapper'
);

Which doesn't work unless your myfdw module is a submodule of multicorn. If you install it as python setup.py install this doesn't happen.

It should instead by this:

CREATE SERVER multicorn_srv foreign data wrapper multicorn options (
    wrapper 'myfdw.ConstantForeignDataWrapper'
    );
    
CREATE FOREIGN TABLE constanttable (
    test character varying,
    test2 character varying
) server multicorn_srv;

I created a quick repo here:

https://bitbucket.org/jir2004/test-multicorn

(this may be more obvious to everyday python developers)

Thanks so much for the time you spent on multicorn! It is very useful!

**Comment by rdunklau** [comment]
Thank you for this report, but I'm not quite sure to understand.

The current documentation on the website is written like you propose it, and I don't see any recent change in the git log.

Could you be more precise please ?
